user:
  kafka:
    store: course-user-store

course:
  kafka:
    server: localhost:9092
    topic: course
    replicas: 3
    partitions: 3
    store: course-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-course
    group-id: apollo-course-group
    offset: latest

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: apollo-course
      function:
        definition: courseProcessor
        bindings:
          courseProcessor-in-0.destination: course
          courseProcessor-out-0.destination: course-state
