user:
  kafka:
    store: course-user-state-store

chapter:
  kafka:
    store: course-chapter-state-store

course:
  kafka:
    server: localhost:9092
    topic: course
    replicas: 1
    partitions: 1
    store: course-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-course
    group-id: apollo-course-group
    offset: latest
    enroll:
      topic: enroll-request
      store: enroll-request-store

spring:
  cloud:
    function:
      definition: courseProcessorState;courseMember;courseChapter;courseEnrollment
    stream:
      kafka:
        streams:
          binder:
            functions:
              courseProcessorState:
                application-id: apollo-course
              courseMember:
                application-id: apollo-course-member
              courseChapter:
                application-id: apollo-course-chapter
              courseEnrollment:
                application-id: apollo-course-enrollment
      bindings:
        courseProcessorState-in-0.destination: ${course.kafka.topic}
        courseProcessorState-out-0.destination: ${course.kafka.store}
        courseMember-in-0.destination: ${course.kafka.topic}
        courseMember-out-0.destination: ${user.kafka.store}
        courseChapter-in-0.destination: ${course.kafka.topic}
        courseChapter-out-0.destination: ${chapter.kafka.store}
        courseEnrollment-in-0.destination: ${course.kafka.enroll.topic}
        courseEnrollment-out-0.destination: ${course.kafka.enroll.store}
server:
  port: 8081
