user:
  kafka:
    store: course-user-state-store

chapter:
  kafka:
    store: course-chapter-state-store

course:
  kafka:
    server: localhost:9092
    topic: course
    replicas: 1
    partitions: 1
    store: course-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-course
    group-id: apollo-course-group
    offset: latest
    enroll:
      topic: enroll-request
      store: enroll-request-store

spring:
  cloud:
    function:
      definition: courseProcessor;
    stream:
      kafka:
        streams:
          binder:
            application-id: apollo-course
      bindings:
        courseProcessor-in-0.destination: course
        courseProcessor-in-1.destination: enroll-request
        courseProcessor-out-0.destination: course-state-store

server:
  port: 8081
